#!/usr/bin/bash

./ga1 input.txt 
echo "Results of file input.txt:"
cat output.txt
./ga1 input2.txt 
echo "Results of file input.txt:"
cat output.txt
./ga1 input3.txt
echo "Results of file input.txt:"
cat output.txt
./ga1 input4.txt
echo "Results of file input.txt:"
cat output.txt
